language: node_js
os:
 - linux
node_js:
  - "14"
  - "12"
  - "11"
  - "10"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
  - 'npm ls > /dev/null'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${TEST-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
    - node_js: "lts/*"
      env: COVERAGE=true
  allow_failures:
    - node_js: "iojs"
    - node_js: "0.12"
    - node_js: "0.10"
